language: python
env:
install:
    - "pip install -U ."
script:
    - "make test"
matrix:
    allow_failures:
        - python: "3.7-dev"
    include:
        - python: "2.7"
        - python: "3.4"
        - python: "3.5"
        - python: "3.6"
        - python: "3.7"
          dist: xenial
          sudo: required
        - python: "3.7-dev"
          dist: xenial
          sudo: required
